import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * SEO metadata
 * Id: b8078397-18a8-48c4-bf50-0897b00e1be8
 * Codename: seo_metadata
 */
export type HasSeoMetadataContentItem = IContentItem<{
  /**
   * Description (text)
   * Required: false
   * Id: 9f1b0ef2-4ff2-494d-86a0-4f38e784de4a
   * Codename: seo_metadata__description
   *
   * Try to accurately summarise content (avoid generic descriptions); Include target keyword(s) where it makes sense; Try to keep it under 160 characters.
   */
  seo_metadata__description: Elements.TextElement;

  /**
   * og:description (text)
   * Required: false
   * Id: 3902f12b-2bc8-4939-afc3-5e824160f61a
   * Codename: seo_metadata__og_description
   *
   * Complement the title to make the snippet as appealing as possible; Keep it short and sweet; If not provided the Description will be used.
   */
  seo_metadata__og_description: Elements.TextElement;

  /**
   * og:image (asset)
   * Required: false
   * Id: db65bd98-9ec8-4145-b3a2-2805207f0429
   * Codename: seo_metadata__og_image
   *
   * Use images with a 1.91:1 ratio and minimum recommended dimensions of 1200x630 for optimal clarity across all devices; See https://developers.facebook.com/docs/sharing/webmasters/images.
   */
  seo_metadata__og_image: Elements.AssetsElement;

  /**
   * og:title (text)
   * Required: false
   * Id: 4f99f771-8427-4f31-947f-44595099e804
   * Codename: seo_metadata__og_title
   *
   * Focus on accuracy, value, and clickability; Try to keep it between 40 to 60 characters; Don't include branding e.g. site name; If not provided the Title will be used.
   */
  seo_metadata__og_title: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: 11ff16b5-10f4-402e-98c4-0ea649878efa
   * Codename: seo_metadata__title
   *
   * Be brief, but descriptive; Use title case; Include target keyword(s) where it makes sense; Try to keep it under 60 characters; Don't include branding e.g. site name.
   */
  seo_metadata__title: Elements.TextElement;
}>;
