import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Author
 * Id: dd4ac826-3fdd-59c6-a99b-a718bcb1631e
 * Codename: author
 */
export type AuthorContentType = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: 8fef09cc-22d3-56ae-ae15-dd8e7748b632
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Picture (asset)
   * Required: false
   * Id: a041beee-f641-5ef9-9661-ef92d96b366f
   * Codename: picture
   */
  picture: Elements.AssetsElement;
}>;
