import { type IContentItem } from '@kontent-ai/delivery-sdk';
import { type HasSeoMetadataContentItem } from '../content-type-snippets/SeoMetadataContentTypeSnippet';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Home
 * Id: eb31c10c-db3f-4f46-b470-1c655c13fdfc
 * Codename: home
 */
export type HomeContentItem = IContentItem<{}> & HasSeoMetadataContentItem;
