import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type AuthorContentType } from './AuthorContentType';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Post
 * Id: bfd389ca-fcf4-5d49-a1f5-70194a96955b
 * Codename: post
 */
export type PostContentType = IContentItem<{
  /**
   * Author (modular_content)
   * Required: false
   * Id: 7c3cc763-6528-51a5-a0d2-13232273e90d
   * Codename: author
   */
  author: Elements.LinkedItemsElement<AuthorContentType>;

  /**
   * Content (rich_text)
   * Required: false
   * Id: 4612eb3e-a0ca-571c-8589-13fd11d7d142
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Cover Image (asset)
   * Required: false
   * Id: 5164e125-3192-5858-a047-0fdef8ea8e56
   * Codename: cover_image
   */
  coverImage: Elements.AssetsElement;

  /**
   * Date (date_time)
   * Required: false
   * Id: 100cc77f-7f41-5d02-84e3-99402488fc34
   * Codename: date
   */
  date: Elements.DateTimeElement;

  /**
   * Excerpt (text)
   * Required: false
   * Id: ae7ce755-21b5-5ea9-b966-05b211b5424a
   * Codename: excerpt
   */
  excerpt: Elements.TextElement;

  /**
   * Slug (url_slug)
   * Required: false
   * Id: de7c3a9a-9e1c-5cf2-b0fb-833e89a70443
   * Codename: slug
   */
  slug: Elements.UrlSlugElement;

  /**
   * Title (text)
   * Required: true
   * Id: 39c4f8a4-0b40-51df-8311-be07206d3482
   * Codename: title
   */
  title: Elements.TextElement;
}>;
