/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Blog Starter
 * Environment: Production
 * Project Id: b78a9cd1-c9b0-0115-36d0-f7fc5a0d4e94
 */
export const assetFolders = {
  /**
   * Authors
   */
  authors: {
    id: '6a7980d7-c91f-5da0-af18-2639f6626fc0',
    name: 'Authors',
    externalId: 'eaf64b25-4cd1-5d71-ba2f-e02e6556213b',
    folders: {},
  },

  /**
   * Post images
   */
  postImages: {
    id: '7259e678-7592-5f11-8c7f-c9b2aa87ebae',
    name: 'Post images',
    externalId: '290176f9-bb83-5d6a-ad07-2843a1dd2208',
    folders: {},
  },
} as const;
