/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Blog Starter
 * Environment: Production
 * Project Id: b78a9cd1-c9b0-0115-36d0-f7fc5a0d4e94
 */
export const contentTypes = {
  /**
   * Author
   */
  author: {
    codename: 'author',
    id: 'dd4ac826-3fdd-59c6-a99b-a718bcb1631e',
    externalId: 'c204b17f-d320-5755-b913-7b4caa8902b6',
    name: 'Author',
    elements: {
      /**
       * Name (text)
       */
      name: {
        codename: 'name',
        id: '8fef09cc-22d3-56ae-ae15-dd8e7748b632',
        externalId: 'fab7d833-5672-5271-ac00-49e6fcf34754',
        name: 'Name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Picture (asset)
       */
      picture: {
        codename: 'picture',
        id: 'a041beee-f641-5ef9-9661-ef92d96b366f',
        externalId: '78b67780-55e4-5b29-903c-de37d3aa263b',
        name: 'Picture',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Post
   */
  post: {
    codename: 'post',
    id: 'bfd389ca-fcf4-5d49-a1f5-70194a96955b',
    externalId: 'b1efdda5-18a3-5445-8ca2-51c252a9ee2d',
    name: 'Post',
    elements: {
      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: '7c3cc763-6528-51a5-a0d2-13232273e90d',
        externalId: 'aa68b9d2-e807-54be-ac82-543ff122b6b2',
        name: 'Author',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '4612eb3e-a0ca-571c-8589-13fd11d7d142',
        externalId: 'f8b91d9f-0a7d-557e-9fe8-ca1203ae4a67',
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Cover Image (asset)
       */
      cover_image: {
        codename: 'cover_image',
        id: '5164e125-3192-5858-a047-0fdef8ea8e56',
        externalId: '8f1bd2ae-b15a-5100-b8ee-b279a87862fb',
        name: 'Cover Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Date (date_time)
       */
      date: {
        codename: 'date',
        id: '100cc77f-7f41-5d02-84e3-99402488fc34',
        externalId: '1739ed56-ccd8-55a3-9cd3-67f09a8073db',
        name: 'Date',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Excerpt (text)
       */
      excerpt: {
        codename: 'excerpt',
        id: 'ae7ce755-21b5-5ea9-b966-05b211b5424a',
        externalId: 'e1461965-9004-500e-9441-39a51aa3088b',
        name: 'Excerpt',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Slug (url_slug)
       */
      slug: {
        codename: 'slug',
        id: 'de7c3a9a-9e1c-5cf2-b0fb-833e89a70443',
        externalId: 'f12efb12-764a-512c-82f8-4423d978b62b',
        name: 'Slug',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '39c4f8a4-0b40-51df-8311-be07206d3482',
        externalId: '933469d0-fe2b-51fa-8f62-600f103aee8b',
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },
} as const;
