/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Blog Starter
 * Environment: Production
 * Project Id: b78a9cd1-c9b0-0115-36d0-f7fc5a0d4e94
 */
export const contentTypeSnippets = {
  /**
   * SEO metadata
   */
  seo_metadata: {
    codename: 'seo_metadata',
    id: 'b8078397-18a8-48c4-bf50-0897b00e1be8',
    externalId: undefined,
    name: 'SEO metadata',
    elements: {
      /**
       * Title (text)
       *
       * Be brief, but descriptive; Use title case; Include target keyword(s) where it makes sense; Try to keep it under 60 characters; Don't include branding e.g. site name.
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: '11ff16b5-10f4-402e-98c4-0ea649878efa',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
      },

      /**
       * Description (text)
       *
       * Try to accurately summarise content (avoid generic descriptions); Include target keyword(s) where it makes sense; Try to keep it under 160 characters.
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '9f1b0ef2-4ff2-494d-86a0-4f38e784de4a',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
      },

      /**
       * og:title (text)
       *
       * Focus on accuracy, value, and clickability; Try to keep it between 40 to 60 characters; Don't include branding e.g. site name; If not provided the Title will be used.
       */
      seo_metadata__og_title: {
        codename: 'seo_metadata__og_title',
        id: '4f99f771-8427-4f31-947f-44595099e804',
        externalId: undefined,
        name: 'og:title',
        required: false,
        type: 'text',
      },

      /**
       * og:description (text)
       *
       * Complement the title to make the snippet as appealing as possible; Keep it short and sweet; If not provided the Description will be used.
       */
      seo_metadata__og_description: {
        codename: 'seo_metadata__og_description',
        id: '3902f12b-2bc8-4939-afc3-5e824160f61a',
        externalId: undefined,
        name: 'og:description',
        required: false,
        type: 'text',
      },

      /**
       * og:image (asset)
       *
       * Use images with a 1.91:1 ratio and minimum recommended dimensions of 1200x630 for optimal clarity across all devices; See https://developers.facebook.com/docs/sharing/webmasters/images.
       */
      seo_metadata__og_image: {
        codename: 'seo_metadata__og_image',
        id: 'db65bd98-9ec8-4145-b3a2-2805207f0429',
        externalId: undefined,
        name: 'og:image',
        required: false,
        type: 'asset',
      },
    },
  },
} as const;
