/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Blog Starter
 * Environment: Production
 * Project Id: b78a9cd1-c9b0-0115-36d0-f7fc5a0d4e94
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
} as const;
